# Build plugin  
ARG GO_VERSION=1.17

FROM golang:$GO_VERSION as builder

ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /protoc-gen-go-enums

# Run plugin
FROM scratch

COPY --from=builder /protoc-gen-go-enums /

ENTRYPOINT ["/protoc-gen-go-enums"]
