version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1
    steps:
      - checkout
      - run: make all generate
      - run: git add --all && git diff --staged --exit-code

workflows:
  version: 2
  development:
    jobs:
      - build
