name: ci
on:
  push:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install tools
        run: make install
      - name: Generate protofiles
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: make generate
      - name: Check code compiles
        run: go test -v -race ./... 
      - name: Check for changes
        run: git add example --all && git diff --exit-code --staged example
  mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Tidy modules
        run: go mod tidy
      - name: Check for changes
        run: git add . && git diff --staged --exit-code
