name: release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  GO_VERSION: "^1.17"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buf_plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Buf registry
        uses: docker/login-action@v1
        with:
          registry: plugins.buf.build
          username: myuser
          password: ${{ secrets.BUF_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.buf.plugin
          push: true
          tags: |
            plugins.buf.build/utilitywarehouse/go-enums:${{github.ref_name}}
